# Form implementation generated from reading ui file 'mulakatlar.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MulakatlarSayfasi(object):
    def setupUi(self, MulakatlarSayfasi):
        MulakatlarSayfasi.setObjectName("MulakatlarSayfasi")
        MulakatlarSayfasi.resize(776, 524)
        self.centralwidget = QtWidgets.QWidget(parent=MulakatlarSayfasi)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(14)
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet("background-color: rgb(255, 246, 201);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame = QtWidgets.QFrame(parent=self.frame_4)
        self.frame.setGeometry(QtCore.QRect(230, 0, 531, 491))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.tableWidgetMul = QtWidgets.QTableWidget(parent=self.frame)
        self.tableWidgetMul.setGeometry(QtCore.QRect(10, 10, 511, 461))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.tableWidgetMul.setFont(font)
        self.tableWidgetMul.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidgetMul.setObjectName("tableWidgetMul")
        self.tableWidgetMul.setColumnCount(3)
        self.tableWidgetMul.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMul.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMul.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMul.setHorizontalHeaderItem(2, item)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_2.setGeometry(QtCore.QRect(10, 0, 215, 481))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.ProjeGelenButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.ProjeGelenButton.setGeometry(QtCore.QRect(0, 190, 211, 61))
        self.ProjeGelenButton.setStyleSheet("background-color: rgb(186, 0, 0);\n"
"border-radius:30px;\n"
"color: rgb(255, 255, 255);")
        self.ProjeGelenButton.setObjectName("ProjeGelenButton")
        self.ProjeGondButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.ProjeGondButton.setGeometry(QtCore.QRect(0, 270, 211, 61))
        self.ProjeGondButton.setStyleSheet("background-color: rgb(186, 0, 0);\n"
"border-radius:30px;\n"
"color: rgb(255, 255, 255);")
        self.ProjeGondButton.setObjectName("ProjeGondButton")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 191, 22))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.pushButton_4.setStyleSheet("background-color: rgb(186, 0, 0);\n"
"border-radius:30px;\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.TercihlerEkraniButtonMul = QtWidgets.QPushButton(parent=self.frame_2)
        self.TercihlerEkraniButtonMul.setGeometry(QtCore.QRect(0, 350, 211, 61))
        self.TercihlerEkraniButtonMul.setStyleSheet("background-color: rgb(186, 0, 0);\n"
"border-radius:30px;\n"
"color: rgb(255, 255, 255);")
        self.TercihlerEkraniButtonMul.setObjectName("TercihlerEkraniButtonMul")
        self.tumMulButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.tumMulButton.setGeometry(QtCore.QRect(0, 110, 211, 61))
        self.tumMulButton.setStyleSheet("background-color: rgb(186, 0, 0);\n"
"border-radius:30px;\n"
"color: rgb(255, 255, 255);")
        self.tumMulButton.setObjectName("tumMulButton")
        self.gridLayout.addWidget(self.frame_4, 0, 0, 1, 1)
        MulakatlarSayfasi.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MulakatlarSayfasi)
        self.statusbar.setObjectName("statusbar")
        MulakatlarSayfasi.setStatusBar(self.statusbar)

        self.retranslateUi(MulakatlarSayfasi)
        QtCore.QMetaObject.connectSlotsByName(MulakatlarSayfasi)

    def retranslateUi(self, MulakatlarSayfasi):
        _translate = QtCore.QCoreApplication.translate
        MulakatlarSayfasi.setWindowTitle(_translate("MulakatlarSayfasi", "MulakatlarSayfasi"))
        item = self.tableWidgetMul.horizontalHeaderItem(0)
        item.setText(_translate("MulakatlarSayfasi", "Adiniz Soyadiniz"))
        item = self.tableWidgetMul.horizontalHeaderItem(1)
        item.setText(_translate("MulakatlarSayfasi", "Proje gonderilis tarihi"))
        item = self.tableWidgetMul.horizontalHeaderItem(2)
        item.setText(_translate("MulakatlarSayfasi", "Projenin gelis tarihi"))
        self.ProjeGelenButton.setText(_translate("MulakatlarSayfasi", "Projesi Gelmis Olanlar"))
        self.ProjeGondButton.setText(_translate("MulakatlarSayfasi", "Projesi Gonderilmis Olanlar"))
        self.pushButton_4.setText(_translate("MulakatlarSayfasi", "ARA"))
        self.TercihlerEkraniButtonMul.setText(_translate("MulakatlarSayfasi", "Tercihler Ekranina Geri Don"))
        self.tumMulButton.setText(_translate("MulakatlarSayfasi", "Tum Mulakatlar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MulakatlarSayfasi = QtWidgets.QMainWindow()
    ui = Ui_MulakatlarSayfasi()
    ui.setupUi(MulakatlarSayfasi)
    MulakatlarSayfasi.show()
    sys.exit(app.exec())
