# Form implementation generated from reading ui file 'tercihlersayfasi.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TercihlerSayfasi(object):
    def setupUi(self, TercihlerSayfasi):
        TercihlerSayfasi.setObjectName("TercihlerSayfasi")
        TercihlerSayfasi.resize(761, 528)
        self.centralwidget = QtWidgets.QWidget(parent=TercihlerSayfasi)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(14)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(255, 246, 201);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.basvruButton = QtWidgets.QPushButton(parent=self.frame)
        self.basvruButton.setGeometry(QtCore.QRect(460, 20, 271, 131))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.basvruButton.setFont(font)
        self.basvruButton.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.basvruButton.setStyleSheet("background-color: rgb(186, 0, 0);\n"
"border-radius:30px;\n"
"color: rgb(255, 255, 255);")
        self.basvruButton.setObjectName("basvruButton")
        self.mentorgorusmesiButton = QtWidgets.QPushButton(parent=self.frame)
        self.mentorgorusmesiButton.setGeometry(QtCore.QRect(460, 170, 271, 131))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.mentorgorusmesiButton.setFont(font)
        self.mentorgorusmesiButton.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.mentorgorusmesiButton.setStyleSheet("background-color: rgb(186, 0, 0);\n"
"border-radius:30px;\n"
"color: rgb(255, 255, 255);")
        self.mentorgorusmesiButton.setObjectName("mentorgorusmesiButton")
        self.mulakatButton = QtWidgets.QPushButton(parent=self.frame)
        self.mulakatButton.setGeometry(QtCore.QRect(460, 330, 271, 131))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.mulakatButton.setFont(font)
        self.mulakatButton.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.mulakatButton.setStyleSheet("background-color: rgb(186, 0, 0);\n"
"border-radius:30px;\n"
"color: rgb(255, 255, 255);")
        self.mulakatButton.setObjectName("mulakatButton")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 431, 461))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.labelResim2 = QtWidgets.QLabel(parent=self.frame_2)
        self.labelResim2.setGeometry(QtCore.QRect(10, 0, 411, 481))
        self.labelResim2.setText("")
        self.labelResim2.setPixmap(QtGui.QPixmap("resimler/werherer logo.png"))
        self.labelResim2.setObjectName("labelResim2")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        TercihlerSayfasi.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=TercihlerSayfasi)
        self.statusbar.setObjectName("statusbar")
        TercihlerSayfasi.setStatusBar(self.statusbar)

        self.retranslateUi(TercihlerSayfasi)
        QtCore.QMetaObject.connectSlotsByName(TercihlerSayfasi)

    def retranslateUi(self, TercihlerSayfasi):
        _translate = QtCore.QCoreApplication.translate
        TercihlerSayfasi.setWindowTitle(_translate("TercihlerSayfasi", "TercihlerSayfasi"))
        self.basvruButton.setText(_translate("TercihlerSayfasi", "Basvurular"))
        self.mentorgorusmesiButton.setText(_translate("TercihlerSayfasi", "Mentor Gorusmesi"))
        self.mulakatButton.setText(_translate("TercihlerSayfasi", "Mulakatlar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TercihlerSayfasi = QtWidgets.QMainWindow()
    ui = Ui_TercihlerSayfasi()
    ui.setupUi(TercihlerSayfasi)
    TercihlerSayfasi.show()
    sys.exit(app.exec())
